version: "3.9"

services:
    backend:
        build: ./
        container_name: backend
        ports:
            - 8000:8000
        env_file:
            - ./envs/.env
        volumes:
            - ./:/app
        command: sh -c
                "python manage.py makemigrations --noinput &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        restart: always
    
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        command: redis-server --save 60 1 --loglevel warning
